apiVersion: v1
kind: Pod
metadata:
  name: portal-noticias
  labels:
    app: portal-noticias
spec:
  containers:
  - name: portal-noticias-container
    image: aluracursos/portal-noticias:1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    env:
      - name: "IP_SISTEMA"
        value: http://192.168.99.100:30001